# Generated by Django 6.0.5 on 2026-05-26 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePrivacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_phone', models.BooleanField(default=False)),
                ('show_email', models.BooleanField(default=False)),
                ('show_location', models.BooleanField(default=True)),
                ('show_followers', models.BooleanField(default=True)),
                ('show_following', models.BooleanField(default=True)),
                ('who_can_message', models.CharField(choices=[('everyone', 'Everyone'), ('followers', 'Followers'), ('nobody', 'Nobody')], default='everyone', max_length=20)),
                ('who_can_follow', models.CharField(choices=[('everyone', 'Everyone'), ('followers', 'Followers'), ('nobody', 'Nobody')], default='everyone', max_length=20)),
                ('show_online_status', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privacy', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Profile Privacy',
            },
        ),
    ]
