# Generated by Django 6.0.5 on 2026-09-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingapplication',
            name='org_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='listingapplication',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
