# Generated by Django 6.0.5 on 2026-09-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0002_listingapplication_org_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listingapplication',
            name='org_name',
        ),
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
