# Generated by Django 6.0.5 on 2026-09-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0003_remove_listingapplication_org_name_post_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='deposit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='listing_type',
            field=models.CharField(choices=[('rental', 'Rental'), ('sale', 'Sale')], default='rental'),
        ),
        migrations.AddField(
            model_name='post',
            name='monthly_installment',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
