# Generated by Django 6.0.5 on 2026-09-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0004_post_deposit_post_listing_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='house_type',
            field=models.CharField(default='single'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.TextField(choices=[('single', 'Single Room'), ('bed_sitter', 'BedSitter'), ('one_bedroom', 'One Bedroom'), ('two_bedroom', 'Two Bedroom'), ('three_plus', 'Three+ Bedroom')], default='pending'),
        ),
    ]
