# Generated by Django 6.0.5 on 2026-09-12 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0005_post_house_type_alter_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='house_type',
            field=models.CharField(choices=[('single', 'Single Room'), ('bed_sitter', 'BedSitter'), ('one_bedroom', 'One Bedroom'), ('two_bedroom', 'Two Bedroom'), ('three_plus', 'Three+ Bedroom')], default='single'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.TextField(choices=[('approved', 'Aproved'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='pending'),
        ),
    ]
