# Generated by Django 6.0.5 on 2026-07-08 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='seller_reply',
            new_name='user_reply',
        ),
        migrations.RemoveField(
            model_name='post',
            name='condition',
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='feed.category'),
        ),
        migrations.DeleteModel(
            name='BuyIntent',
        ),
    ]
