# Generated by Django 6.0.5 on 2026-07-08 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_rename_seller_reply_review_user_reply_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='negotiable',
        ),
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video')], default='text', max_length=10),
        ),
    ]
