# Generated by Django 6.0.5 on 2026-07-13 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_alter_post_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='saves_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
