# Generated by Django 6.0.5 on 2026-07-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_post_saves_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='image_url',
        ),
        migrations.AddField(
            model_name='message',
            name='media_url',
            field=models.ImageField(blank=True, null=True, upload_to='messages/images/'),
        ),
        migrations.AddField(
            model_name='message',
            name='video_url',
            field=models.FileField(blank=True, null=True, upload_to='messages/videos/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('offer', 'Offer')], default='text', max_length=10),
        ),
    ]
