# Generated by Django 6.0.5 on 2026-07-17 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_remove_message_image_url_message_media_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='media_url',
            new_name='image_url',
        ),
    ]
