# Generated by Django 6.0.5 on 2026-07-18 17:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_rename_media_url_message_image_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationDeletes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'conversation_deletes',
            },
        ),
        migrations.CreateModel(
            name='MessageDeletes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'message_deletes',
            },
        ),
        migrations.RemoveConstraint(
            model_name='messageread',
            name='uq_message_reads_msg_user',
        ),
        migrations.AddConstraint(
            model_name='messageread',
            constraint=models.UniqueConstraint(fields=('user', 'message'), name='uq_message_reads_msg_user'),
        ),
        migrations.AddField(
            model_name='conversationdeletes',
            name='conversation',
            field=models.ForeignKey(db_column='message_id', on_delete=django.db.models.deletion.CASCADE, related_name='conversation_deletes', to='feed.conversation'),
        ),
        migrations.AddField(
            model_name='conversationdeletes',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='conversation_deletes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messagedeletes',
            name='message',
            field=models.ForeignKey(db_column='message_id', on_delete=django.db.models.deletion.CASCADE, related_name='message_deletes', to='feed.message'),
        ),
        migrations.AddField(
            model_name='messagedeletes',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='message_deletes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='conversationdeletes',
            constraint=models.UniqueConstraint(fields=('user', 'conversation'), name='uq_conversation_delete_per_user'),
        ),
        migrations.AddConstraint(
            model_name='messagedeletes',
            constraint=models.UniqueConstraint(fields=('user', 'message'), name='uq_message_delete_per_user'),
        ),
        migrations.AlterUniqueTogether(
            name='messagedeletes',
            unique_together={('user', 'message')},
        ),
    ]
