# Generated by Django 6.0.5 on 2026-07-18 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0008_conversationdeletes_messagedeletes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationdeletes',
            name='conversation',
            field=models.ForeignKey(db_column='conversation_id', on_delete=django.db.models.deletion.CASCADE, related_name='conversation_deletes', to='feed.conversation'),
        ),
    ]
