# Generated by Django 6.0.5 on 2026-07-19 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0009_alter_conversationdeletes_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationdeletes',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
