# Generated by Django 6.0.5 on 2026-07-25 08:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0010_conversationdeletes_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(('message_type__in', ['text', 'image', 'video', 'offer'])), name='valid_message_type'),
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.CheckConstraint(condition=models.Q(('post_type__in', ['text', 'image', 'video'])), name='valid_post_type'),
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['approved', 'pending', 'rejected'])), name='valid_status'),
        ),
        migrations.AddConstraint(
            model_name='postreport',
            constraint=models.CheckConstraint(condition=models.Q(('action_taken__in', ['none', 'warn', 'suspend', 'ban'])), name='valid_action_type'),
        ),
    ]
