# Generated by Django 6.0.5 on 2026-07-26 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0011_message_valid_message_type_post_valid_post_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='replied_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_replies', to='feed.comment'),
        ),
    ]
