# Generated by Django 6.0.5 on 2026-07-27 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0012_comment_replied_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='deleted_body',
            field=models.CharField(blank=True, null=True),
        ),
    ]
