# Generated by Django 6.0.5 on 2026-07-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0013_comment_deleted_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='postvideo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
