# Generated by Django 6.0.5 on 2026-07-08 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommunityBuyIntent',
        ),
    ]
