# Generated by Django 6.0.5 on 2026-07-08 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_delete_communitybuyintent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitypost',
            name='condition',
        ),
        migrations.AddField(
            model_name='communitypost',
            name='post_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video')], default='text', max_length=10),
        ),
    ]
