# Generated by Django 6.0.5 on 2026-07-08 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_remove_communitypost_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitypost',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
