# Generated by Django 6.0.5 on 2026-07-13 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_alter_communitypost_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitypost',
            name='negotiable',
        ),
    ]
