# Generated by Django 6.0.5 on 2026-07-13 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_remove_communitypost_negotiable'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypost',
            name='saves_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
