# Generated by Django 6.0.5 on 2026-07-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_communitypost_saves_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitycategorypost',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
