# Generated by Django 6.0.5 on 2026-07-25 08:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_alter_communitycategorypost_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='communitypost',
            constraint=models.CheckConstraint(condition=models.Q(('post_type__in', ['text', 'image', 'video'])), name='valid_post_type_com'),
        ),
        migrations.AddConstraint(
            model_name='communitypost',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['approved', 'pending', 'rejected'])), name='valid_status_com'),
        ),
    ]
