# Generated by Django 6.0.5 on 2026-07-27 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_communitypost_valid_post_type_com_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypostcomment',
            name='deleted_body',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communitypostcomment',
            name='replied_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_replies', to='groups.communitypostcomment'),
        ),
    ]
