# Generated by Django 6.0.5 on 2026-07-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0009_communitypostcomment_deleted_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitypost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='communitypostimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='communitypostvideo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
