# Generated by Django 6.0.5 on 2026-09-25 06:52

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0012_alter_communitypostvideo_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypost',
            name='client_upload_id',
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='communitypostvideo',
            name='processing_status',
            field=models.CharField(choices=[('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='processing', max_length=10),
        ),
        migrations.AlterField(
            model_name='communitypostvideo',
            name='video',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='posts/videos/'),
        ),
    ]
